// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static PDiffy.Features.Error.ErrorController Error = new PDiffy.Features.Error.T4MVC_ErrorController();
    public static PDiffy.Features.History.HistoryController History = new PDiffy.Features.History.T4MVC_HistoryController();
    public static PDiffy.Features.ImageDifferences.ImageDifferencesController ImageDifferences = new PDiffy.Features.ImageDifferences.T4MVC_ImageDifferencesController();
    public static PDiffy.Features.ImageViewer.ImageViewerController ImageViewer = new PDiffy.Features.ImageViewer.T4MVC_ImageViewerController();
    public static PDiffy.Features.Setup.SetupController Setup = new PDiffy.Features.Setup.T4MVC_SetupController();
    public static PDiffy.Features.TextDifferences.TextDifferencesController TextDifferences = new PDiffy.Features.TextDifferences.T4MVC_TextDifferencesController();
    public static T4MVC.ImageComparisonsController ImageComparisons = new T4MVC.ImageComparisonsController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
    public static T4MVC.TextComparisonsController TextComparisons = new T4MVC.TextComparisonsController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string Differences_generated_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Differences.generated.min.js") ? Url("Differences.generated.min.js") : Url("Differences.generated.js");
        public static readonly string History_generated_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/History.generated.min.js") ? Url("History.generated.min.js") : Url("History.generated.js");
        public static readonly string Shared_generated_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Shared.generated.min.js") ? Url("Shared.generated.min.js") : Url("Shared.generated.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Styles {
        private const string URLPATH = "~/Styles";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string Differences_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Differences.min.css") ? Url("Differences.min.css") : Url("Differences.css");
             
        public static readonly string Error_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Error.min.css") ? Url("Error.min.css") : Url("Error.css");
             
        public static readonly string History_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/History.min.css") ? Url("History.min.css") : Url("History.css");
             
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public const string Differences_generated_js = "~/Scripts/Differences.generated.js"; 
                public const string History_generated_js = "~/Scripts/History.generated.js"; 
                public const string Shared_generated_js = "~/Scripts/Shared.generated.js"; 
            }
        }
        public static partial class Styles 
        {
            public static class Assets
            {
                public const string Differences_css = "~/Styles/Differences.css";
                public const string Error_css = "~/Styles/Error.css";
                public const string History_css = "~/Styles/History.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


